services:
  media-organizer:
    build: .
    container_name: media-organizer
    restart: unless-stopped
    environment:
      CONFIG_FILE: /config/settings.json
      LOG_LEVEL: INFO

    volumes:
      # 只挂载允许 AutoReel 访问的媒体工作目录
      - /volumeUSB1/usbshare/emby:/host/emby
      # 配置文件与状态数据库
      - ./config:/config
